# Generated by Django 3.1.5 on 2021-01-20 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kankor_id', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('grand_father_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('main_language', models.CharField(default='دری', max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('birth_year', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True)),
                ('page_number', models.CharField(blank=True, max_length=100, null=True)),
                ('register_number', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(max_length=200)),
                ('graduation_year_from_school', models.DateField(blank=True, null=True)),
                ('kankor_year', models.DateField(blank=True, null=True)),
                ('kankor_score', models.FloatField(blank=True, null=True)),
                ('main_address', models.CharField(blank=True, max_length=500)),
                ('current_address', models.CharField(blank=True, max_length=500)),
                ('relative', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('job', models.CharField(blank=True, max_length=200)),
                ('relative_phone_number', models.CharField(blank=True, max_length=100)),
                ('student_registration_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='student.jpg', null=True, upload_to='students/images')),
            ],
        ),
    ]
