# Generated by Django 3.1.5 on 2021-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year_from_school',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='kankor_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='kankor_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='main_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
