# Generated by Django 3.1.5 on 2021-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210120_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_year', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='studets/upload/')),
            ],
        ),
    ]
