# Generated by Django 3.1.5 on 2021-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studenttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kankor_id',
            field=models.CharField(max_length=200),
        ),
    ]
