# Generated by Django 3.1.5 on 2021-01-20 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210120_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kankor_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_registration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
