# Generated by Django 3.1.5 on 2021-01-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210120_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='student.jpg', upload_to='students/images'),
        ),
    ]
