# Generated by Django 3.1.5 on 2021-01-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210120_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTest',
        ),
    ]
