# Generated by Django 3.1.5 on 2021-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('birth_year', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20)),
                ('nationality', models.CharField(max_length=200)),
                ('army_job', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=10)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True)),
                ('register_number', models.CharField(blank=True, max_length=200, null=True)),
                ('page_number', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=200, null=True)),
                ('high_school_name', models.CharField(max_length=200)),
                ('high_school_location', models.CharField(max_length=200)),
                ('high_school_start', models.DateField(blank=True, null=True)),
                ('high_school_end', models.DateField(blank=True, null=True)),
                ('hight_school_field', models.CharField(blank=True, max_length=200, null=True)),
                ('high_school_diploma', models.ImageField(upload_to='teacher/school/')),
                ('high_school_percentage', models.CharField(max_length=200)),
                ('bachelor_university_name', models.CharField(max_length=200)),
                ('bachelor_university_location', models.CharField(max_length=200)),
                ('bachelor_start', models.DateField(blank=True, null=True)),
                ('bachelor_end', models.DateField(blank=True, null=True)),
                ('bachelor_field', models.CharField(max_length=200)),
                ('bachelor_diploma', models.ImageField(upload_to='teacher/bachelor/')),
                ('bachelor_percentage', models.CharField(max_length=200)),
                ('master_university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('master_university_location', models.CharField(blank=True, max_length=200, null=True)),
                ('master_start', models.DateField(blank=True, null=True)),
                ('master_end', models.DateField(blank=True, null=True)),
                ('master_field', models.CharField(blank=True, max_length=200, null=True)),
                ('master_diploma', models.ImageField(blank=True, null=True, upload_to='teacher/master/')),
                ('master_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_university_location', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_start', models.DateField(blank=True, null=True)),
                ('phd_end', models.DateField(blank=True, null=True)),
                ('phd_field', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_diploma', models.ImageField(blank=True, null=True, upload_to='teacher/school/')),
                ('phd_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('job_position', models.CharField(blank=True, max_length=200, null=True)),
                ('job_start_date', models.DateField(blank=True, null=True)),
                ('job_end_date', models.DateField(blank=True, null=True)),
                ('recomandition_letter', models.ImageField(blank=True, null=True, upload_to='teacher/jon/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/images')),
            ],
        ),
    ]
