# Generated by Django 3.1.5 on 2021-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210124_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='recomandition_letter2',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/job2/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='recomandition_letter3',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/job3/'),
        ),
    ]
